
image:
  repository: ghcr.io/ilia-medvedev-codefresh/s3-aggregated-metrics-collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Mode to run collector in, currently only "cronjob" is supported
mode: "cronjob"
# Cronjob configuration
cronjob:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  backoffLimit: 1
  concurrencyPolicy: "Forbid"
  restartPolicy: "OnFailure"
# Configurations for the collector
collector:
  # Aggregation prefix depth
  prefixDepth: 1
  openTelemetryGrpcEndpoint: "localhost:4317"
  # Specify list of bucket to collect metrics for
  buckets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
