name: Publish main image and chart

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract abbreviated commit SHA
      - name: Get abbreviated commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Build and push multi-arch image
      - name: Build and push image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}/collector:${{ env.COMMIT_SHA }} \
            --push .

  package-and-push-helm-chart:
    name: Package and Push Helm Chart
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v3

      # Extract abbreviated commit SHA
      - name: Get abbreviated commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Update Helm chart version
      - name: Update Helm chart version
        run: |
          sed -i "s/^version:.*/version: 0.0.0-${{ env.COMMIT_SHA }}/" .deploy/charts/s3-aggregated-metrics-collector/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ env.COMMIT_SHA }}\"/" .deploy/charts/s3-aggregated-metrics-collector/Chart.yaml

      # Package Helm chart
      - name: Package Helm chart
        run: |
          helm package .deploy/charts/s3-aggregated-metrics-collector --destination .deploy/charts/

      # Push Helm chart to OCI registry
      - name: Push Helm chart to OCI registry
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          helm push .deploy/charts/s3-aggregated-metrics-collector-*.tgz oci://ghcr.io/${{ github.repository }}/charts
